export enum CommercialStatus {
  DRAFT = 'draft',
  PENDING_APPROVAL = 'pending_approval',
  APPROVED = 'approved',
  REJECTED = 'rejected',
  CANCELLED = 'cancelled'
}

export enum OperationalStatus {
  PENDING = 'pending',
  PICKING = 'picking',
  SEPARATED = 'separated',
  INVOICED = 'invoiced',
  SHIPPED = 'shipped',
  DELIVERED = 'delivered',
  CANCELLED = 'cancelled'
}

export enum OrderEventType {
  ORDER_CREATED = 'ORDER_CREATED',
  APPROVAL_REQUESTED = 'APPROVAL_REQUESTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  
  // Fulfillment & Logistics Events
  PICKING_ASSIGNED = 'PICKING_ASSIGNED',
  PICKING_STARTED = 'PICKING_STARTED',
  ITEM_PICKED = 'ITEM_PICKED',
  PICKING_COMPLETED = 'PICKING_COMPLETED',
  PICKING_EXCEPTION_CREATED = 'PICKING_EXCEPTION_CREATED',
  PICKING_EXCEPTION_APPROVED = 'PICKING_EXCEPTION_APPROVED',
  PICKING_CANCELLED = 'PICKING_CANCELLED',
  INVOICE_CREATED = 'INVOICE_CREATED',
  INVOICE_SUBMITTED_TO_PROVIDER = 'INVOICE_SUBMITTED_TO_PROVIDER',
  INVOICE_AUTHORIZED = 'INVOICE_AUTHORIZED',
  INVOICE_REJECTED = 'INVOICE_REJECTED',
  INVOICE_ISSUED = 'INVOICE_ISSUED',
  INVOICE_CANCELLED = 'INVOICE_CANCELLED',
  SHIPMENT_CREATED = 'SHIPMENT_CREATED',
  SHIPMENT_READY = 'SHIPMENT_READY',
  SHIPMENT_PICKED_UP = 'SHIPMENT_PICKED_UP',
  SHIPMENT_DISPATCHED = 'SHIPMENT_DISPATCHED',
  SHIPMENT_DELIVERED = 'SHIPMENT_DELIVERED',
  SHIPMENT_FAILED = 'SHIPMENT_FAILED',
  ORDER_SHIPPED = 'ORDER_SHIPPED',
  SHIPPED = 'SHIPPED',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED'
}

export interface OrderTransitionResult {
  commercialStatus: CommercialStatus;
  operationalStatus: OperationalStatus;
  eventType: OrderEventType;
  expectedVersion: number;
  reason?: string;
}
