-- Migration: create sync_settings_to_catalogs trigger/function
-- Location: supabase/migrations/001_sync_settings_to_public_catalogs.sql

-- Ajuste: converte banners (text[] em settings) para jsonb em public_catalogs
-- e replica vários campos de settings para public_catalogs em uma operação atômica.

CREATE OR REPLACE FUNCTION public.sync_settings_to_catalogs()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.public_catalogs (
        user_id,
        catalog_slug,
        store_name,
        logo_url,
        primary_color,
        secondary_color,
        footer_message,
        is_active,
        show_sale_price,
        show_cost_price,
        header_background_color,
        enable_stock_management,
        show_installments,
        max_installments,
        cash_price_discount_percent,
        price_password_hash,
        top_benefit_image_url,
        top_benefit_height,
        top_benefit_text_size,
        top_benefit_bg_color,
        top_benefit_text_color,
        top_benefit_text,
        show_top_benefit_bar,
        show_top_info_bar,
        footer_background_color,
        phone,
        email,
        top_benefit_image_fit,
        top_benefit_image_scale,
        representative_name,
        whatsapp_message_template,
        font_family,
        font_url,
        top_benefit_text_align,
        top_benefit_image_align,
        banners_mobile,
        share_banner_url,
        og_image_url,
        price_unlock_mode,
        top_benefit_mode,
        top_benefit_speed,
        top_benefit_animation,
        header_text_color,
        header_icon_bg_color,
        header_icon_color,
        about_text,
        welcome_text,
        headline,
        cover_image,
        cover_image_fit,
        cover_image_height,
        cover_image_position,
        cover_image_offset_x,
        cover_image_offset_y,
        store_banner_meta,
        instagram_url,
        facebook_url,
        linkedin_url,
        whatsapp_url,
        catalog_pdf_url,
        footer_text_color,
        gallery_title,
        gallery_subtitle,
        gallery_title_color,
        gallery_subtitle_color,
        cover_headline_font_size,
        cover_headline_offset_x,
        cover_headline_offset_y,
        cover_headline_z_index,
        cover_headline_wrap,
        cover_headline_force_two_lines,
        banner_mode,
        header_color,
        title_color,
        icon_color,
        is_price_protected,
        show_shipping,
        hide_delivery_address,
        show_discount,
        show_old_price,
        show_filter_price,
        show_filter_category,
        show_filter_bestseller,
        show_filter_new,
        show_delivery_address_checkout,
        show_payment_method_checkout,
        gallery_urls,
        custom_primary_color,
        custom_logo_url,
        -- TRATAMENTO DE BANNERS: converte text[] -> jsonb
        banners
    )
    VALUES (
        NEW.user_id,
        NEW.catalog_slug,
        NEW.name,
        NEW.logo_url,
        NEW.primary_color,
        NEW.secondary_color,
        NEW.footer_message,
        NEW.is_active,
        NEW.show_sale_price,
        NEW.show_cost_price,
        NEW.header_background_color,
        NEW.enable_stock_management,
        NEW.show_installments,
        NEW.max_installments,
        NEW.cash_price_discount_percent,
        NEW.price_password_hash,
        NEW.top_benefit_image_url,
        NEW.top_benefit_height,
        NEW.top_benefit_text_size,
        NEW.top_benefit_bg_color,
        NEW.top_benefit_text_color,
        NEW.top_benefit_text,
        NEW.show_top_benefit_bar,
        NEW.show_top_info_bar,
        NEW.footer_background_color,
        NEW.phone,
        NEW.email,
        NEW.top_benefit_image_fit,
        NEW.top_benefit_image_scale,
        NEW.representative_name,
        NEW.whatsapp_message_template,
        NEW.font_family,
        NEW.font_url,
        NEW.top_benefit_text_align,
        NEW.top_benefit_image_align,
        NEW.banners_mobile,
        NEW.share_banner_url,
        NEW.og_image_url,
        NEW.price_unlock_mode,
        NEW.top_benefit_mode,
        NEW.top_benefit_speed,
        NEW.top_benefit_animation,
        NEW.header_text_color,
        NEW.header_icon_bg_color,
        NEW.header_icon_color,
        NEW.about_text,
        NEW.welcome_text,
        NEW.headline,
        NEW.cover_image,
        NEW.cover_image_fit,
        NEW.cover_image_height,
        NEW.cover_image_position,
        NEW.cover_image_offset_x,
        NEW.cover_image_offset_y,
        NEW.store_banner_meta,
        NEW.instagram_url,
        NEW.facebook_url,
        NEW.linkedin_url,
        NEW.whatsapp_url,
        NEW.catalog_pdf_url,
        NEW.footer_text_color,
        NEW.gallery_title,
        NEW.gallery_subtitle,
        NEW.gallery_title_color,
        NEW.gallery_subtitle_color,
        NEW.cover_headline_font_size,
        NEW.cover_headline_offset_x,
        NEW.cover_headline_offset_y,
        NEW.cover_headline_z_index,
        NEW.cover_headline_wrap,
        NEW.cover_headline_force_two_lines,
        NEW.banner_mode,
        NEW.header_color,
        NEW.title_color,
        NEW.icon_color,
        NEW.is_price_protected,
        NEW.show_shipping,
        NEW.hide_delivery_address,
        NEW.show_discount,
        NEW.show_old_price,
        NEW.show_filter_price,
        NEW.show_filter_category,
        NEW.show_filter_bestseller,
        NEW.show_filter_new,
        NEW.show_delivery_address_checkout,
        NEW.show_payment_method_checkout,
        NEW.gallery_urls,
        NEW.custom_primary_color,
        NEW.custom_logo_url,
        -- conversão de banners: text[] -> jsonb
        to_jsonb(NEW.banners)
    )
    ON CONFLICT (user_id) DO UPDATE SET
        catalog_slug = EXCLUDED.catalog_slug,
        store_name = EXCLUDED.store_name,
        logo_url = EXCLUDED.logo_url,
        primary_color = EXCLUDED.primary_color,
        secondary_color = EXCLUDED.secondary_color,
        footer_message = EXCLUDED.footer_message,
        is_active = EXCLUDED.is_active,
        show_sale_price = EXCLUDED.show_sale_price,
        show_cost_price = EXCLUDED.show_cost_price,
        header_background_color = EXCLUDED.header_background_color,
        enable_stock_management = EXCLUDED.enable_stock_management,
        show_installments = EXCLUDED.show_installments,
        max_installments = EXCLUDED.max_installments,
        cash_price_discount_percent = EXCLUDED.cash_price_discount_percent,
        price_password_hash = EXCLUDED.price_password_hash,
        top_benefit_image_url = EXCLUDED.top_benefit_image_url,
        top_benefit_height = EXCLUDED.top_benefit_height,
        top_benefit_text_size = EXCLUDED.top_benefit_text_size,
        top_benefit_bg_color = EXCLUDED.top_benefit_bg_color,
        top_benefit_text_color = EXCLUDED.top_benefit_text_color,
        top_benefit_text = EXCLUDED.top_benefit_text,
        show_top_benefit_bar = EXCLUDED.show_top_benefit_bar,
        show_top_info_bar = EXCLUDED.show_top_info_bar,
        footer_background_color = EXCLUDED.footer_background_color,
        phone = EXCLUDED.phone,
        email = EXCLUDED.email,
        top_benefit_image_fit = EXCLUDED.top_benefit_image_fit,
        top_benefit_image_scale = EXCLUDED.top_benefit_image_scale,
        representative_name = EXCLUDED.representative_name,
        whatsapp_message_template = EXCLUDED.whatsapp_message_template,
        font_family = EXCLUDED.font_family,
        font_url = EXCLUDED.font_url,
        top_benefit_text_align = EXCLUDED.top_benefit_text_align,
        top_benefit_image_align = EXCLUDED.top_benefit_image_align,
        banners_mobile = EXCLUDED.banners_mobile,
        share_banner_url = EXCLUDED.share_banner_url,
        og_image_url = EXCLUDED.og_image_url,
        price_unlock_mode = EXCLUDED.price_unlock_mode,
        top_benefit_mode = EXCLUDED.top_benefit_mode,
        top_benefit_speed = EXCLUDED.top_benefit_speed,
        top_benefit_animation = EXCLUDED.top_benefit_animation,
        header_text_color = EXCLUDED.header_text_color,
        header_icon_bg_color = EXCLUDED.header_icon_bg_color,
        header_icon_color = EXCLUDED.header_icon_color,
        about_text = EXCLUDED.about_text,
        welcome_text = EXCLUDED.welcome_text,
        headline = EXCLUDED.headline,
        cover_image = EXCLUDED.cover_image,
        cover_image_fit = EXCLUDED.cover_image_fit,
        cover_image_height = EXCLUDED.cover_image_height,
        cover_image_position = EXCLUDED.cover_image_position,
        cover_image_offset_x = EXCLUDED.cover_image_offset_x,
        cover_image_offset_y = EXCLUDED.cover_image_offset_y,
        store_banner_meta = EXCLUDED.store_banner_meta,
        instagram_url = EXCLUDED.instagram_url,
        facebook_url = EXCLUDED.facebook_url,
        linkedin_url = EXCLUDED.linkedin_url,
        whatsapp_url = EXCLUDED.whatsapp_url,
        catalog_pdf_url = EXCLUDED.catalog_pdf_url,
        footer_text_color = EXCLUDED.footer_text_color,
        gallery_title = EXCLUDED.gallery_title,
        gallery_subtitle = EXCLUDED.gallery_subtitle,
        gallery_title_color = EXCLUDED.gallery_title_color,
        gallery_subtitle_color = EXCLUDED.gallery_subtitle_color,
        cover_headline_font_size = EXCLUDED.cover_headline_font_size,
        cover_headline_offset_x = EXCLUDED.cover_headline_offset_x,
        cover_headline_offset_y = EXCLUDED.cover_headline_offset_y,
        cover_headline_z_index = EXCLUDED.cover_headline_z_index,
        cover_headline_wrap = EXCLUDED.cover_headline_wrap,
        cover_headline_force_two_lines = EXCLUDED.cover_headline_force_two_lines,
        banner_mode = EXCLUDED.banner_mode,
        header_color = EXCLUDED.header_color,
        title_color = EXCLUDED.title_color,
        icon_color = EXCLUDED.icon_color,
        is_price_protected = EXCLUDED.is_price_protected,
        show_shipping = EXCLUDED.show_shipping,
        hide_delivery_address = EXCLUDED.hide_delivery_address,
        show_discount = EXCLUDED.show_discount,
        show_old_price = EXCLUDED.show_old_price,
        show_filter_price = EXCLUDED.show_filter_price,
        show_filter_category = EXCLUDED.show_filter_category,
        show_filter_bestseller = EXCLUDED.show_filter_bestseller,
        show_filter_new = EXCLUDED.show_filter_new,
        show_delivery_address_checkout = EXCLUDED.show_delivery_address_checkout,
        show_payment_method_checkout = EXCLUDED.show_payment_method_checkout,
        gallery_urls = EXCLUDED.gallery_urls,
        custom_primary_color = EXCLUDED.custom_primary_color,
        custom_logo_url = EXCLUDED.custom_logo_url,
        -- ATUALIZAÇÃO BANNERS:
        banners = EXCLUDED.banners,
        updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Criar trigger na tabela settings
DROP TRIGGER IF EXISTS trigger_sync_settings ON public.settings;
CREATE TRIGGER trigger_sync_settings
AFTER INSERT OR UPDATE ON public.settings
FOR EACH ROW EXECUTE FUNCTION public.sync_settings_to_catalogs();
