-- Migration: Fix sync_settings_to_catalogs trigger function to resolve NULL catalog_slug, store_name, and logo_url with fallbacks
-- Date: 2026-09-10

CREATE OR REPLACE FUNCTION public.sync_settings_to_catalogs()
RETURNS TRIGGER AS $$
DECLARE
    v_effective_slug TEXT;
    v_effective_store_name TEXT;
    v_effective_logo_url TEXT;
BEGIN
    -- Resolve catalog_slug: use NEW.catalog_slug if non-empty,
    -- otherwise fallback to existing catalog_slug in public_catalogs or settings,
    -- or generate a clean fallback slug from name + user_id prefix.
    v_effective_slug := COALESCE(
        NULLIF(TRIM(NEW.catalog_slug), ''),
        (SELECT NULLIF(TRIM(catalog_slug), '') FROM public.public_catalogs WHERE user_id = NEW.user_id),
        (SELECT NULLIF(TRIM(catalog_slug), '') FROM public.settings WHERE user_id = NEW.user_id AND user_id <> NEW.user_id),
        regexp_replace(lower(COALESCE(NULLIF(TRIM(NEW.name), ''), 'catalogo')), '[^a-z0-9]+', '-', 'g') || '-' || substring(NEW.user_id::text from 1 for 8)
    );

    -- Resolve store_name: use NEW.name if non-empty,
    -- otherwise fallback to representative_name, existing public_catalogs.store_name, profiles.full_name, or default.
    v_effective_store_name := COALESCE(
        NULLIF(TRIM(NEW.name), ''),
        NULLIF(TRIM(NEW.representative_name), ''),
        (SELECT NULLIF(TRIM(store_name), '') FROM public.public_catalogs WHERE user_id = NEW.user_id),
        (SELECT NULLIF(TRIM(full_name), '') FROM public.profiles WHERE id = NEW.user_id),
        'Catálogo RepVendas'
    );

    -- Resolve logo_url: use NEW.logo_url if non-empty,
    -- otherwise fallback to existing public_catalogs.logo_url or settings.logo_url.
    v_effective_logo_url := COALESCE(
        NULLIF(TRIM(NEW.logo_url), ''),
        (SELECT NULLIF(TRIM(logo_url), '') FROM public.public_catalogs WHERE user_id = NEW.user_id),
        (SELECT NULLIF(TRIM(logo_url), '') FROM public.settings WHERE user_id = NEW.user_id AND user_id <> NEW.user_id)
    );

    INSERT INTO public.public_catalogs (
        user_id,
        catalog_slug,
        store_name,
        logo_url,
        primary_color,
        secondary_color,
        footer_message,
        is_active,
        show_sale_price,
        show_cost_price,
        header_background_color,
        enable_stock_management,
        show_installments,
        max_installments,
        cash_price_discount_percent,
        price_password_hash,
        top_benefit_image_url,
        top_benefit_height,
        top_benefit_text_size,
        top_benefit_bg_color,
        top_benefit_text_color,
        top_benefit_text,
        show_top_benefit_bar,
        show_top_info_bar,
        footer_background_color,
        phone,
        email,
        top_benefit_image_fit,
        top_benefit_image_scale,
        representative_name,
        whatsapp_message_template,
        font_family,
        font_url,
        top_benefit_text_align,
        top_benefit_image_align,
        banners_mobile,
        share_banner_url,
        og_image_url,
        price_unlock_mode,
        top_benefit_mode,
        top_benefit_speed,
        top_benefit_animation,
        header_text_color,
        header_icon_bg_color,
        header_icon_color,
        about_text,
        welcome_text,
        headline,
        cover_image,
        cover_image_fit,
        cover_image_height,
        cover_image_position,
        cover_image_offset_x,
        cover_image_offset_y,
        store_banner_meta,
        instagram_url,
        facebook_url,
        linkedin_url,
        whatsapp_url,
        catalog_pdf_url,
        footer_text_color,
        gallery_title,
        gallery_subtitle,
        gallery_title_color,
        gallery_subtitle_color,
        cover_headline_font_size,
        cover_headline_offset_x,
        cover_headline_offset_y,
        cover_headline_z_index,
        cover_headline_wrap,
        cover_headline_force_two_lines,
        banner_mode,
        header_color,
        title_color,
        icon_color,
        is_price_protected,
        show_shipping,
        hide_delivery_address,
        show_discount,
        show_old_price,
        show_filter_price,
        show_filter_category,
        show_filter_bestseller,
        show_filter_new,
        show_delivery_address_checkout,
        show_payment_method_checkout,
        gallery_urls,
        custom_primary_color,
        custom_logo_url,
        banners
    )
    VALUES (
        NEW.user_id,
        v_effective_slug,
        v_effective_store_name,
        v_effective_logo_url,
        NEW.primary_color,
        NEW.secondary_color,
        NEW.footer_message,
        NEW.is_active,
        NEW.show_sale_price,
        NEW.show_cost_price,
        NEW.header_background_color,
        NEW.enable_stock_management,
        NEW.show_installments,
        NEW.max_installments,
        NEW.cash_price_discount_percent,
        NEW.price_password_hash,
        NEW.top_benefit_image_url,
        NEW.top_benefit_height,
        NEW.top_benefit_text_size,
        NEW.top_benefit_bg_color,
        NEW.top_benefit_text_color,
        NEW.top_benefit_text,
        NEW.show_top_benefit_bar,
        NEW.show_top_info_bar,
        NEW.footer_background_color,
        NEW.phone,
        NEW.email,
        NEW.top_benefit_image_fit,
        NEW.top_benefit_image_scale,
        NEW.representative_name,
        NEW.whatsapp_message_template,
        NEW.font_family,
        NEW.font_url,
        NEW.top_benefit_text_align,
        NEW.top_benefit_image_align,
        NEW.banners_mobile,
        NEW.share_banner_url,
        NEW.og_image_url,
        NEW.price_unlock_mode,
        NEW.top_benefit_mode,
        NEW.top_benefit_speed,
        NEW.top_benefit_animation,
        NEW.header_text_color,
        NEW.header_icon_bg_color,
        NEW.header_icon_color,
        NEW.about_text,
        NEW.welcome_text,
        NEW.headline,
        NEW.cover_image,
        NEW.cover_image_fit,
        NEW.cover_image_height,
        NEW.cover_image_position,
        NEW.cover_image_offset_x,
        NEW.cover_image_offset_y,
        NEW.store_banner_meta,
        NEW.instagram_url,
        NEW.facebook_url,
        NEW.linkedin_url,
        NEW.whatsapp_url,
        NEW.catalog_pdf_url,
        NEW.footer_text_color,
        NEW.gallery_title,
        NEW.gallery_subtitle,
        NEW.gallery_title_color,
        NEW.gallery_subtitle_color,
        NEW.cover_headline_font_size,
        NEW.cover_headline_offset_x,
        NEW.cover_headline_offset_y,
        NEW.cover_headline_z_index,
        NEW.cover_headline_wrap,
        NEW.cover_headline_force_two_lines,
        NEW.banner_mode,
        NEW.header_color,
        NEW.title_color,
        NEW.icon_color,
        NEW.is_price_protected,
        NEW.show_shipping,
        NEW.hide_delivery_address,
        NEW.show_discount,
        NEW.show_old_price,
        NEW.show_filter_price,
        NEW.show_filter_category,
        NEW.show_filter_bestseller,
        NEW.show_filter_new,
        NEW.show_delivery_address_checkout,
        NEW.show_payment_method_checkout,
        NEW.gallery_urls,
        NEW.custom_primary_color,
        NEW.custom_logo_url,
        to_jsonb(NEW.banners)
    )
    ON CONFLICT (user_id) DO UPDATE SET
        catalog_slug = COALESCE(NULLIF(TRIM(EXCLUDED.catalog_slug), ''), public_catalogs.catalog_slug, v_effective_slug),
        store_name = COALESCE(NULLIF(TRIM(EXCLUDED.store_name), ''), public_catalogs.store_name, v_effective_store_name),
        logo_url = COALESCE(NULLIF(TRIM(EXCLUDED.logo_url), ''), public_catalogs.logo_url, v_effective_logo_url),
        primary_color = EXCLUDED.primary_color,
        secondary_color = EXCLUDED.secondary_color,
        footer_message = EXCLUDED.footer_message,
        is_active = EXCLUDED.is_active,
        show_sale_price = COALESCE(EXCLUDED.show_sale_price, public_catalogs.show_sale_price),
        show_cost_price = COALESCE(EXCLUDED.show_cost_price, public_catalogs.show_cost_price),
        header_background_color = EXCLUDED.header_background_color,
        enable_stock_management = EXCLUDED.enable_stock_management,
        show_installments = EXCLUDED.show_installments,
        max_installments = EXCLUDED.max_installments,
        cash_price_discount_percent = EXCLUDED.cash_price_discount_percent,
        price_password_hash = EXCLUDED.price_password_hash,
        top_benefit_image_url = COALESCE(EXCLUDED.top_benefit_image_url, public_catalogs.top_benefit_image_url),
        top_benefit_height = COALESCE(EXCLUDED.top_benefit_height, public_catalogs.top_benefit_height),
        top_benefit_text_size = COALESCE(EXCLUDED.top_benefit_text_size, public_catalogs.top_benefit_text_size),
        top_benefit_bg_color = COALESCE(EXCLUDED.top_benefit_bg_color, public_catalogs.top_benefit_bg_color),
        top_benefit_text_color = COALESCE(EXCLUDED.top_benefit_text_color, public_catalogs.top_benefit_text_color),
        top_benefit_text = COALESCE(EXCLUDED.top_benefit_text, public_catalogs.top_benefit_text),
        show_top_benefit_bar = COALESCE(EXCLUDED.show_top_benefit_bar, public_catalogs.show_top_benefit_bar),
        show_top_info_bar = COALESCE(EXCLUDED.show_top_info_bar, public_catalogs.show_top_info_bar),
        footer_background_color = EXCLUDED.footer_background_color,
        phone = EXCLUDED.phone,
        email = EXCLUDED.email,
        top_benefit_image_fit = COALESCE(EXCLUDED.top_benefit_image_fit, public_catalogs.top_benefit_image_fit),
        top_benefit_image_scale = COALESCE(EXCLUDED.top_benefit_image_scale, public_catalogs.top_benefit_image_scale),
        representative_name = EXCLUDED.representative_name,
        whatsapp_message_template = EXCLUDED.whatsapp_message_template,
        font_family = EXCLUDED.font_family,
        font_url = EXCLUDED.font_url,
        top_benefit_text_align = COALESCE(EXCLUDED.top_benefit_text_align, public_catalogs.top_benefit_text_align),
        top_benefit_image_align = COALESCE(EXCLUDED.top_benefit_image_align, public_catalogs.top_benefit_image_align),
        banners_mobile = EXCLUDED.banners_mobile,
        share_banner_url = EXCLUDED.share_banner_url,
        og_image_url = EXCLUDED.og_image_url,
        price_unlock_mode = COALESCE(EXCLUDED.price_unlock_mode, public_catalogs.price_unlock_mode),
        top_benefit_mode = COALESCE(EXCLUDED.top_benefit_mode, public_catalogs.top_benefit_mode),
        top_benefit_speed = COALESCE(EXCLUDED.top_benefit_speed, public_catalogs.top_benefit_speed),
        top_benefit_animation = COALESCE(EXCLUDED.top_benefit_animation, public_catalogs.top_benefit_animation),
        header_text_color = EXCLUDED.header_text_color,
        header_icon_bg_color = EXCLUDED.header_icon_bg_color,
        header_icon_color = EXCLUDED.header_icon_color,
        about_text = EXCLUDED.about_text,
        welcome_text = EXCLUDED.welcome_text,
        headline = EXCLUDED.headline,
        cover_image = EXCLUDED.cover_image,
        cover_image_fit = EXCLUDED.cover_image_fit,
        cover_image_height = EXCLUDED.cover_image_height,
        cover_image_position = EXCLUDED.cover_image_position,
        cover_image_offset_x = EXCLUDED.cover_image_offset_x,
        cover_image_offset_y = EXCLUDED.cover_image_offset_y,
        store_banner_meta = EXCLUDED.store_banner_meta,
        instagram_url = EXCLUDED.instagram_url,
        facebook_url = EXCLUDED.facebook_url,
        linkedin_url = EXCLUDED.linkedin_url,
        whatsapp_url = EXCLUDED.whatsapp_url,
        catalog_pdf_url = EXCLUDED.catalog_pdf_url,
        footer_text_color = EXCLUDED.footer_text_color,
        gallery_title = EXCLUDED.gallery_title,
        gallery_subtitle = EXCLUDED.gallery_subtitle,
        gallery_title_color = EXCLUDED.gallery_title_color,
        gallery_subtitle_color = EXCLUDED.gallery_subtitle_color,
        cover_headline_font_size = EXCLUDED.cover_headline_font_size,
        cover_headline_offset_x = EXCLUDED.cover_headline_offset_x,
        cover_headline_offset_y = EXCLUDED.cover_headline_offset_y,
        cover_headline_z_index = EXCLUDED.cover_headline_z_index,
        cover_headline_wrap = EXCLUDED.cover_headline_wrap,
        cover_headline_force_two_lines = EXCLUDED.cover_headline_force_two_lines,
        banner_mode = EXCLUDED.banner_mode,
        header_color = EXCLUDED.header_color,
        title_color = EXCLUDED.title_color,
        icon_color = EXCLUDED.icon_color,
        is_price_protected = EXCLUDED.is_price_protected,
        show_shipping = EXCLUDED.show_shipping,
        hide_delivery_address = EXCLUDED.hide_delivery_address,
        show_discount = EXCLUDED.show_discount,
        show_old_price = EXCLUDED.show_old_price,
        show_filter_price = EXCLUDED.show_filter_price,
        show_filter_category = EXCLUDED.show_filter_category,
        show_filter_bestseller = EXCLUDED.show_filter_bestseller,
        show_filter_new = EXCLUDED.show_filter_new,
        show_delivery_address_checkout = EXCLUDED.show_delivery_address_checkout,
        show_payment_method_checkout = EXCLUDED.show_payment_method_checkout,
        gallery_urls = EXCLUDED.gallery_urls,
        custom_primary_color = EXCLUDED.custom_primary_color,
        custom_logo_url = EXCLUDED.custom_logo_url,
        banners = EXCLUDED.banners,
        updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Backfill public_catalogs for any rows that might have empty/null store_name
UPDATE public.public_catalogs pc
SET store_name = COALESCE(
    (SELECT NULLIF(TRIM(s.name), '') FROM public.settings s WHERE s.user_id = pc.user_id),
    (SELECT NULLIF(TRIM(p.full_name), '') FROM public.profiles p WHERE p.id = pc.user_id),
    'Catálogo RepVendas'
)
WHERE COALESCE(TRIM(pc.store_name), '') = '';
